### ISSUE TITLE
Documentation points to purl as client for pman.

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [FNNDSC/pman#20]
Is purl still supported client for pman? Or is it pfurl?

- If purl, is still supported, we need to update the code at https://github.com/FNNDSC/pman/blob/master/pman/__init__.py#L8 , so that client can communicate as expected in https://github.com/FNNDSC/pman/wiki/pman-command:-run.

- If not, the documentation needs to be updated to reflect that pfurl is official client along with examples.

cc @danmcp

**Comment by danmcp** [comment]
@rudolphpienaar Can you comment on this?  I am not positive on the history with purl vs pfurl but I have always been using pfurl so I am guessing the doc is out of date.

**Comment by rudolphpienaar** [comment]
``purl`` is a deprecated earlier version of ``pfurl``. The ``pman`` documentation is rather old, I'm afraid. I'll look into this tomorrow. Thanks for the catch! But basically where ever you see ``purl`` just substitute with ``pfurl``
